### ISSUE TITLE
US 01.03.01 As an organizer, I want to send notifications to all attendees through the app.

### ISSUE THREAD

**Issue by alastairvox** [CMPUT301W24T29/QuickScanQuestPro#16]
US 01.03.01 As an organizer, I want to send notifications to all attendees through the app.

### Acceptance Criteria
- Button in the event details that allows an organizer viewing an event they created to send an announcement to all attendees (option to send notification to just checked in attendees, or to checked in and interested attendees?)
- attendees receive a notification on their phone with the announcement
- going to the event details page will show a list containing the announcement that was sent

Story Points: 3
Risk Level: Low

### Released for halfway point?
No

### Progress / Completion Criteria
- [x] Code
- [x] Javadocs
- [x] Tests
- [x] UI Mockup
- [x] Storyboard
- [ ] UML

**Comment by jojojojimmy** [comment]
i have implemented this:
1. each organizer gets a microphone button thats available to them if they access the attendees list
2. the organizer can write his own custom title and body for the notification.
