### ISSUE TITLE
US 04.03.01 As an administrator, I want to be able to remove images.

### ISSUE THREAD

**Issue by josephhdu** [CMPUT301W24T29/QuickScanQuestPro#23]
US 04.03.01 As an administrator, I want to be able to remove images.

### Acceptance Criteria
- button that allows an admin to see a list of images from events and profiles in the app (either together or two different lists)
- button for each image that allows the admin to delete the image from the event/user profile and will stay gone

Story Points: 1
Risk Level: Low

### Released for halfway point?
No

### Progress / Completion Criteria
- [x] Code
  - [x] pull list of events and users from database
- [x] Javadocs
- [x] Tests
- [x] UI Mockup
- [x] Storyboard
- [x] UML

**Comment by ericmah123** [comment]
March 4: We implemented it where we read the boolean of admin for each user in the database. Which subsequently updates which profile is shown (admin vs regular user). 

- We still need to get information from the database and populate the listview for each aspect of the admin abilities
- Add the ability to remove stuff from the database
