### ISSUE TITLE
US 01.09.01 As an organizer, I want to see how many times an attendee has checked into an event.

### ISSUE THREAD

**Issue by iftemum** [CMPUT301W24T29/QuickScanQuestPro#28]
### Acceptance Criteria
- Button to take organizer to the details of an event they created
- Button to see attendees of that event and how many times each has checked in

Story Points: 1
Risk Level: low

### Released for halfway point?
No

### Progress
- [x] Code
- [x] Javadocs
- [x] Tests
- [ ] UML
- [ ] UI Mockup
- [ ] Storyboard

**Comment by alastairvox** [comment]
Clarification Provided: We are keeping track of how many times an attendee has checked into a single event, like if they are leaving the event and then re-entering later.
