### ISSUE TITLE
US 02.04.01 As an attendee, I want to view event details and announcements within the app.

### ISSUE THREAD

**Issue by jojojojimmy** [CMPUT301W24T29/QuickScanQuestPro#9]
US 02.04.01 As an attendee, I want to view event details and announcements within the app.

### Acceptance Criteria
- Users can click on an event on their device to view more info about the event and view announcements about the event they wish to attend

Story Points: 2
Risk Level: Medium

### Released for halfway point?
Yes

### Progress
- [x] Code
- [x] Javadocs
- [x] Tests
- [x] UML
- [x] UI Mockup
- [x] Storyboard

**Comment by sdbelhum** [comment]
- Created Fragment with test Event details showing poster, title, event details, announcements
